### ISSUE TITLE
There's no usable example on how to create config.yml

### ISSUE THREAD

**Issue by kworr** [timescale/promscale#1093]
I'm trying to set up a service, but I don't like showing password on process list or passing everything through the environment. However if I create a file with any single line promscale says it doesn't know such variables.

**Comment by JamesGuthrie** [comment]
@kworr this is an example of what the config file could look like:

```yaml
# config.yml
db-ssl-mode: disable
db-user: postgres
db-port: 5432
db-password: password
db-name: postgres
```

Can you give that a try? I will add an example to the documentation.

**Comment by kworr** [comment]
Big thanks, I was puzzled whether I should use underscores or dots, so I totally forgot about dashes.

**Comment by JamesGuthrie** [comment]
> Big thanks, I was puzzled whether I should use underscores or dots, so I totally forgot about dashes.

It's a pleasure! To clarify, the format is the exact same as CLI flags. As of Promscale 0.8.0 we've restructured the CLI flags , so the file example that I gave should actually be:

```yaml
# config.yml
db.ssl-mode: disable
db.user: postgres
db.port: 5432
db.password: password
db.name: postgres
```
