### ISSUE TITLE
Promscale don't received metrics in some irregular interval

### ISSUE THREAD

**Issue by oersted81** [timescale/promscale#1278]
Hi, we want to use promscale(timescaledb-2-postgresql-14) but we still encounter issue that promscale  irregularly stop receiving metrics from prometheus(prometheus-2.29.1). All data in prometheus are continuously without any drops so problem must by in promscale. We have deployed prosmacle and prometheus on the same host in lxd containers. Prometheus remote_write is:

```
remote_write:
- url: "http://promscale:9201/write/"
  remote_timeout: 2m
  queue_config:
    capacity: 10000
    max_samples_per_send: 3000
    batch_send_deadline: 1m
    min_shards: 20
    max_shards: 20
    min_backoff: 100ms
    max_backoff: 10s
```
I will attache log error if any occur soon. We are trying to tune up capacity, max_samples_per_send and timeouts, min/max shards parameters, but without success. Any idea will be appreciated.
Metrics drops in grafana(promscale datasource):
![Selection_677](https://user-images.githubusercontent.com/43389569/160981509-19645e89-7768-4ee4-b74f-19208498f4b9.png)
