### ISSUE TITLE
Alert and runbook for duplicate samples

### ISSUE THREAD

**Issue by Harkishen-Singh** [timescale/promscale#1687]
This issue is based on a discusion in [#promscale slack thread](https://timescaledb.slack.com/archives/C011FC0PPC5/p1665473308182439?thread_ts=1664949014.661779&cid=C011FC0PPC5).

Promscale logs duplicate samples for reasons like:
1. Prometheus retrying a batch
2. Wrongly configured HA cluster

In both the above cases, poor ingestion throughput is the impact. We should alert the user about this early to limit the effect on ingestion and recommend necessary mitigation steps in the runbooks.

**Comment by paulfantom** [comment]
Good example of such alert from [prometheus mixin](https://github.com/prometheus/prometheus/blob/main/documentation/prometheus-mixin/alerts.libsonnet#L129-L142):
```
alert: PrometheusDuplicateTimestamps
annotations:
  description: Prometheus {{$labels.instance}} is dropping {{ printf "%.4g" $value  }}
    samples/s with different values but duplicated timestamp.
  summary: Prometheus is dropping samples with duplicate timestamps.
expr: |
  rate(prometheus_target_scrapes_sample_duplicate_timestamp_total{job="prometheus"}[5m]) > 0
for: 10m
labels:
  severity: warning
```
