### ISSUE TITLE
Maintenance jobs unable to compress all chunks

### ISSUE THREAD

**Issue by mikberg** [timescale/promscale#1741]
**Describe the bug**

My Promscale instance is nearly constantly alerting
`PromscaleMaintenanceJobNotKeepingup`, which seems to be because
`promscale_sql_database_chunks_metrics_uncompressed_count` never quite reaches
the set minimum of
[10](https://github.com/timescale/promscale/blob/c3ad7d388187806d29912696e7e740889570639c/docs/mixin/alerts/alerts.yaml#L268).
Instead, it seems to vary in the interval between 600 and ~1100, depending on maintenance job settings.

I have tried running `call prom_api.execute_maintenance();` manually, repeatedly (in a loop) and tried an aggressive schedule for maintenance jobs, running 4x every 5 minutes. They still seem to hit a "floor" around 600 uncompressed chunks.

Unfortunately, I haven't been able to run the full debugging query from the runbook, as the database goes into recovery mode whenever I try.

**To Reproduce**

Not sure.

**Expected behavior**

`promscale_sql_database_chunks_metrics_uncompressed_count` hitting values `< 10` after maintenace jobs are done.

**Screenshots**
<img width="1474" alt="Screenshot 2022-11-04 at 11 29 37" src="https://user-images.githubusercontent.com/3372191/199951576-a27afbf8-8590-4992-8261-1b97c2b095ff.png">

**Configuration (as applicable)**
 - Promscale Connector:

```yaml
startup.dataset.config: |
  metrics:
    compress_data: true  # default
    default_retention_period: 90d  # default
    default_chunk_interval: 2h  # default is 8h; reduced in effort to mitigate PromscaleMaintenanceJobRunningTooLong
  traces:
    default_retention_period: 30d  # default
```

 - TimescaleDB:

```yaml
shared_buffers: 1280MB
effective_cache_size: 3840MB
maintenance_work_mem: 640MB
work_mem: 8738kB
timescaledb.max_background_workers: 8
max_worker_processes: 13
max_parallel_workers_per_gather: 1
max_parallel_workers: 2
wal_buffers: 16MB
min_wal_size: 2GB
max_wal_size: 4GB
checkpoint_timeout: 900
bgwriter_delay: 10ms
bgwriter_lru_maxpages: 100000
default_statistics_target: 500
random_page_cost: 1.1
checkpoint_completion_target: 0.9
max_connections: 75
max_locks_per_transaction: 64
autovacuum_max_workers: 10
autovacuum_naptime: 10
effective_io_concurrency: 256
timescaledb.last_tuned: '2022-10-28T08:48:02Z'
timescaledb.last_tuned_version: '0.14.1'
```

**Version**
 - Distribution/OS: 
 - Promscale: 0.16.0, 0.7.0 (extension)
 - TimescaleDB: 2.8.1

**Additional context**

 - PostgreSQL running via [Crunchy postgres-operator](https://github.com/CrunchyData/postgres-operator), database is allocated 8 GB memory, on average using about 5-6 GB.
 - Average ingest at around 2000 samples/sec per Grafana dashboard.
