### ISSUE TITLE
Permission denied  for table s1_scrape_series_added from stdin binary

### ISSUE THREAD

**Issue by prime-minister-of-fun** [timescale/promscale#1769]
**Describe the bug**
I'm attempting to run the database connection for promscale with a user that isn't a superuser.
Judging by looking into the steps before the stdin error below, it looks like a temp table is created, then it is supposed to be populated with binary data from stdin.
```
ERROR:  permission denied for table s1_scrape_series_added
2022-11-29 20:00:58.947 UTC [37841] STATEMENT:  copy "s1_scrape_series_added" ( "time", "value", "series_id" ) from stdin binary;
2022-11-29 20:00:58.948 UTC [37841] LOG:  statement: rollback
```

**To Reproduce**
Change config.yaml to use a login URI with an account that isn't a superuser and has all privileges to the database to which it connects.
Restart pod.
   

**Expected behavior**
I expect the non-superuser to be able to ingest data.

**Configuration (as applicable)**
 - Promscale Connector:
```
   startup.install-extensions: true


    db.uri: postgres://promscale_user:promscale_secret@pgsql0:5432/promscale?sslmode=allow


    cache.memory-target: '80%'

    metrics.rules.config-file: /etc/config/promscale-rules.yaml
    metrics.alertmanager.notification-queue-capacity: 100

    web.auth.username: foo
    web.auth.password: sock_it_to_me

    telemetry.log.format: logfmt
    telemetry.log.throughput-report-interval: 1m

    startup.dataset.config: |
          default_chunk_interval: 6h
          compress_data: true
          ha_lease_refresh: 10s
          ha_lease_timeout: 1m
          default_retention_period: 90d
          traces:
            default_retention_period: 30d
```
 - TimescaleDB:
Apache licensed version installed via the apt repo and running inside Postgresql 14.

**Version**
 - Distribution/OS: 
    docker.io/ubuntu:focal
 - Promscale: 
   PROMSCALE_VERSION="0.16.0"
 - TimescaleDB:
   Whatever ships with Postgresql 14.  It's all installed with apt.
**Additional context**
Let me know if you are open to a feature request to reduce privileges to a non-superuser with "all privileges" inside a database.
As the app runs now, it cannot be deployed inside my company's existing postgresql environment because of the superuser requirement.  Spinning up a standalone instance of PostgreSQL isn't going to be popular with multiple work groups.  Example: roles inherit group permissions, networking permissions, compliance standards.  
Using a lower-privileged user is a requirement to getting the non-free version of TimeseriesDB.
The workflow would go something like:
Have a SQL script in the repo I can submit to the DBA.  
DBA closes ticket as completed as well as sending me credentials.
Spin up promscale pod.
Profit!
