### ISSUE TITLE
Document remote write parameters

### ISSUE THREAD

**Issue by cevian** [timescale/promscale#366]
Document suggested parameter for remote write https://prometheus.io/docs/practices/remote_write/
e.g.  capacity shards etc

**Comment by wilfriedroset** [comment]
Thank you for this, I will definitively tests those settings. In the meantime, would it be a useful information at the bottom of the [README](https://github.com/timescale/promscale/blob/master/README.md#configuring-prometheus-to-filter-which-metrics-are-sent-optional) as there is already an example and like to newly create file for more information?

Something like this or with the optional lines commented
```
remote_write:
 - url: "http://promscale_connector:9201/write"
   queue_config:
    batch_send_deadline: 30s
    capacity: 10000
    min_shards: 4
   write_relabel_configs:
      - source_labels: [__name__]
        regex: 'go_.*'
        action: drop
```

What do you think?
