### ISSUE TITLE
Poor performance from Timescale Cloud and Promscale

### ISSUE THREAD

**Issue by patstrom** [timescale/promscale#427]
In December I evaluated Timescale Cloud and Promscale for handling a moderate (~20GiB data over a 3w period) amount of metrics and experienced fairly poor performance.

I set up the TimescaleDB cluster via the console of Timescale Cloud and I haven't made any configuration changes to the database itself. As for the Prometheus-Promscale cluster we are running [Prometheus Operator](https://github.com/prometheus-operator/prometheus-operator) and really like it so I opted to include Promscale as a sidecar for each pod in the 2-replica Prometheus Cluster. Below is the Kubernetes manifest that was deployed during the evaluation period.

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: promscale
  namespace: monitoring
  labels:
    prometheus: promscale
spec:
  replicas: 2
  version: v2.19.0
  serviceAccountName: prometheus
  serviceMonitorSelector: {}
  serviceMonitorNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles
      prometheus: promscale
  resources:
    requests:
      cpu: "2000m"
      memory: 8Gi
    limits:
      memory: 10Gi
  securityContext:
    runAsUser: 1000
    fsGroup: 2000
    runAsNonRoot: true
  containers:
    - name: promscale-connector
      image: timescale/promscale:0.1.3
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 9201
          name: connector-port
      args:
        - --leader-election-pg-advisory-lock-id=1
        - --leader-election-pg-advisory-lock-prometheus-timeout=6s
      env:
        - name: TS_PROM_DB_PORT
          value: ""
        - name: TS_PROM_DB_USER
          value: ""
        - name: TS_PROM_DB_PASSWORD
          value: ""
        - name: TS_PROM_DB_HOST
          value: ""        
        - name: TS_PROM_DB_NAME
          value: metrics
  remoteWrite:
    - url: http://127.0.0.1:9201/write
  remoteRead:
    - url: http://127.0.0.1:9201/read
```

(the allocated resources are quite excessive since in certain cases we need to run very heavy queries for debugging)

I deployed this alongside our existing Prometheus cluster so I could compare them side-by-side. Both clusters scraped the exact same metrics, but the existing one handles it's own storage with the default TSDB.

TimescaleDB itself basically raced to 100% CPU usage and the cluster was rebuilt daily. Below is the CPU & Disk usage for TimescaleDB during the period I evaluated it.

![timescaledb](https://user-images.githubusercontent.com/8882361/104705190-e3a56b80-5719-11eb-9b85-c6187cf7a038.png)

The Prometheus-Promscale cluster unfortunately didn't fare much better. It uses significantly more of both CPU and memory and it is more inconsistent with it compared to the existing Prometheus cluster. During this it also performed a lot worse than the Promtheus cluster when querying. I tried doing a PromQL query that looked similar to `request_latency_nanoseconds_count{namespace="production"}` and it just timed out. I assume this is due to the TimescaleDB cluster being overloaded.

Below is the CPU & Memory usage of the regular Prometheus cluster and the Prometheus-Promscale cluster during the same time period scraping the same metrics. The Promscale graphs level out about when the TimescaleDB cluster was shut down due to lack of credits.

![prometheus_promscale](https://user-images.githubusercontent.com/8882361/104705993-da68ce80-571a-11eb-8923-e552f99804c3.png)

I also noticed a lot of logs about `duplicate data in sample` if that is helpful.

As I mentioned in the video call our ambition is to be able to store user-specific request metrics. I.e. attach labels such as api client ids and configuration headers and such to the "regular" request metrics and use the same solution for operational and usage metrics. Due to the resulting label cardinality being very high this is not recommended for standard Prometheus, which is why we want to use TimescaleDB.

**Comment by cevian** [comment]
For those following the issue: we assume that this issue is because of a bottleneck in the db for some reason. But we don't know for sure. We will be investigating in the next few days

**Comment by patstrom** [comment]
Any update on this?

**Comment by Harkishen-Singh** [comment]
@patstrom , could you confirm if there is proper connectivity between Prometheus-Promscale pair and Timescale cloud?

I feel the reason of such high memory usage is that Promscale may not be able to reach Timescale cloud easily, leading to fall back in Prometheus and hence the Prometheus shard queues have data filled in memory for hours, which is probably the reason behind high memory usage.

**Comment by patstrom** [comment]
What would constitute "proper connectivity"? I set it up using the VPC Peering provided by Timescale Cloud and it does insert metrics into Postgres. I assumed that would be enough.

**Comment by Harkishen-Singh** [comment]
Does Prometheus logs contain words like `resharding...` or `retrying..`?

**Comment by patstrom** [comment]
No. The Promscale connector printed lots of "duplicate data in sample" and the Prometheus container printed lots like so:

```
ts=2020-12-23T20:51:59.878Z caller=dedupe.go:112 component=remote level=warn remote_name=b51834 url=http://127.0.0.1:9201/write msg="Failed to send batch, retrying" err="Post \"http://127.0.0.1:9201/write\": context deadline exceeded" 
ts=2020-12-23T20:52:14.150Z caller=dedupe.go:112 component=remote level=warn remote_name=b51834 url=http://127.0.0.1:9201/write msg="Failed to send batch, retrying" err="Post \"http://127.0.0.1:9201/write\": read tcp 127.0.0.1:49546->127.0.0.1:9201: read: connection reset by peer" 
ts=2020-12-23T20:52:14.150Z caller=dedupe.go:112 component=remote level=warn remote_name=b51834 url=http://127.0.0.1:9201/write msg="Failed to send batch, retrying" err="Post \"http://127.0.0.1:9201/write\": EOF" 
ts=2020-12-23T20:52:14.790Z caller=dedupe.go:112 component=remote level=warn remote_name=b51834 url=http://127.0.0.1:9201/write msg="Failed to send batch, retrying" err="Post \"http://127.0.0.1:9201/write\": read tcp 127.0.0.1:49184->127.0.0.1:9201: read: connection reset by peer" 
ts=2020-12-23T20:52:14.892Z caller=dedupe.go:112 component=remote level=warn remote_name=b51834 url=http://127.0.0.1:9201/write msg="Failed to send batch, retrying" err="Post \"http://127.0.0.1:9201/write\": dial tcp 127.0.0.1:9201: connect: connection refused" 
ts=2020-12-23T20:52:16.306Z caller=dedupe.go:112 component=remote level=warn remote_name=b51834 url=http://127.0.0.1:9201/write msg="Failed to send batch, retrying" err="Post \"http://127.0.0.1:9201/write\": read tcp 127.0.0.1:50328->127.0.0.1:9201: read: connection reset by peer" 
ts=2020-12-23T21:00:01.483Z caller=dedupe.go:112 component=remote level=warn remote_name=b51834 url=http://127.0.0.1:9201/write msg="Failed to send batch, retrying" err="Post \"http://127.0.0.1:9201/write\": context deadline exceeded"
```

for a while an then eventually the promscale connector would be reachable again and it prints

```
level=info ts=2020-12-23T21:00:02.951Z caller=compact.go:495 component=tsdb msg="write block" mint=1608746400000 maxt=1608753600000 ulid=01ET8PDH5HDG6ED3S61RC819VR duration=2.90122004s 
level=info ts=2020-12-23T21:00:03.378Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=102.445791ms 
level=info ts=2020-12-23T21:00:04.357Z caller=compact.go:495 component=tsdb msg="write block" mint=1608746400000 maxt=1608753600000 ulid=01ET8PDJH63ZV38W512JYHD9VZ duration=2.911111267s 
level=info ts=2020-12-23T21:00:04.802Z caller=head.go:792 component=tsdb msg="Head GC completed" duration=100.314234ms 
```

If you provide me with an email address I can send you all the logs from all containers during the test run.

**Comment by Harkishen-Singh** [comment]
Do your exporters expose timestamps as well? if yes, then, would you mind saying if the value of `honor_timestamps` in prometheus config file.

The deadline might have been exceeded due to logging (behaviour of logging is blocking). This has been fixed now and the release `0.1.5` (would be out soon) has the fix. But anyways, could you try increasing the deadline to `30s` or so and see if it helps?

Could you share your throughput shown by Promscale? (or in mail if you want)

> If you provide me with an email address I can send you all the logs from all containers during the test run.

definitely. you can mail me at `harkishen@timescale.com` or `promscale@timescale.com` (if you mail here, do let someone know).

**Comment by patstrom** [comment]
I just sent you an email with the logs!

Prometheus-Operator generates the prometheus config file so I am unsure. I haven't specified anything so I assume it is still the default value.

**Comment by Harkishen-Singh** [comment]
Thank you for the mail.
I will take a look and try to replicate the same shortly. I will get back to you if something else is required or if something comes out of the investigation.

**Comment by patstrom** [comment]
Hello! I have now had time to re-evaluate this with the latest version!

My first try was with a newly created `Timescale-pro-50-4gb-2cpu-compute-optimized (2 CPU, 4 GB RAM, 50 GB storage, backup up to 3 days with PITR) high availability pair` on Postgres 13.2. I then deployed Prometheus and one replica of the Promscale connectior in the same pod using Prometheus-Operator

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: promscale
  namespace: monitoring
  labels:
    prometheus: promscale
spec:
  type: ClusterIP
  selector:
    prometheus: promscale
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: connector-port
...
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: promscale
  namespace: monitoring
  labels:
    prometheus: promscale
spec:
  replicas: 1
  version: v2.26.0
  serviceAccountName: prometheus
  serviceMonitorSelector: {}
  serviceMonitorNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles
      prometheus: promscale
  resources:
    requests:
      cpu: "1000m"
      memory: 2Gi
    limits:
      memory: 3Gi
  securityContext:
    runAsUser: 1000
    fsGroup: 2000
    runAsNonRoot: true
  containers:
    - name: promscale-connector
      image: timescale/promscale:0.3.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 9201
          name: connector-port
          #args:
          #  - --leader-election-pg-advisory-lock-id=1
          #  - --leader-election-pg-advisory-lock-prometheus-timeout=6s
      env:
        - name: TS_PROM_DB_PORT
          value: "12224"
        - name: TS_PROM_DB_USER
          value: tsdbadmin
        - name: TS_PROM_DB_PASSWORD
          value: 
        - name: TS_PROM_DB_HOST
          value: 
        - name: TS_PROM_DB_NAME
          value: metrics
  remoteWrite:
    - url: http://127.0.0.1:9201/write
      remoteTimeout: 30s
      queueConfig:
        capacity: 10000
        maxSamplesPerSend: 3000
        batchSendDeadline: 10s
        minShards: 4
        maxShards: 200
        minBackoff: 100ms
        maxBackoff: 10s
  remoteRead:
    - url: http://127.0.0.1:9201/read
      readRecent: true
...
```

The results were disappointing as the database chocked up after a couple of hours at 100% CPU usage and thus all queries timed out.

For my second test I tried it with a newly created `Timescale-basic-100-compute-optimized (4 CPU, 16 GB RAM, 100 GB storage, backup up to 2 days with PITR) ` on Postgres 12.6. I used the same Prometheus/Promscale manifest.

This worked out a lot better since the database didn't choke. I ran it for a couple of days and was happy with the metrics on the database (CPU usage, disk utilization & compression rates). Although it still uses _more_ memory than vanilla Prometheus for whatever reason. I also tried a HA manifest that had 2 replicas and the `--leader-election` flags and it worked well. Below are images of the metrics

![timescale_cpu_disk](https://user-images.githubusercontent.com/8882361/115202127-5d246f80-a0f6-11eb-93fa-c212dc0f5cbb.png)
![promscale_cpu_memory](https://user-images.githubusercontent.com/8882361/115202132-5f86c980-a0f6-11eb-9979-27b20bac55a9.png)

Just as before the top two panels are our existing Prometheus cluster (2 replicas with their own EBS storage) and the bottom two panels are the ones backed by their own Promscale Connector with the TimescaleCloud database as the storage layer. The yellow line in the bottom panels is the second replica from when I tried out the HA manifest. The resource usage feels a lot more reasonable now. Well done!

Unfortunately the query performance for certain queries was significantly worse than the Prometheus cluster. So much so that when Prometheus could reliably finish a query in ~10seconds Promscale took up to a minute and regularly timed out.

Below are two Promql queries, their respective postgresql query (from the logs) as well as how long it took them

```
https://grafana.abiosgaming.com/api/datasources/proxy/17/api/v1/query_range?query=histogram_quantile(0.99, sum by ( method, le)(rate(atlas_request_latency_nanoseconds_bucket{namespace="production"} [1m])))&start=1618466400&end=1618552800&step=120

[tsdb-3f573f18-1] 2021-04-16T06:02:01.916541 [postgresql-12] [15-1] pid=178306,user=tsdbadmin,db=metrics,app=promscale@0.3.0,client=10.0.11.210 LOG: duration: 9197.893 ms execute lrupsc_822_7: SELECT series.labels, result.time_array, result.value_array
[tsdb-3f573f18-1] 2021-04-16T06:02:01.916923 [postgresql-12] [15-2] FROM "prom_data_series"."atlas_request_latency_nanoseconds_bucket" series
[tsdb-3f573f18-1] 2021-04-16T06:02:01.916964 [postgresql-12] [15-3] INNER JOIN LATERAL (
[tsdb-3f573f18-1] 2021-04-16T06:02:01.916988 [postgresql-12] [15-4] SELECT array_agg(time) as time_array, array_agg(value) as value_array
[tsdb-3f573f18-1] 2021-04-16T06:02:01.917016 [postgresql-12] [15-5] FROM
[tsdb-3f573f18-1] 2021-04-16T06:02:01.917056 [postgresql-12] [15-6] (
[tsdb-3f573f18-1] 2021-04-16T06:02:01.917087 [postgresql-12] [15-7] SELECT time, value
[tsdb-3f573f18-1] 2021-04-16T06:02:01.917122 [postgresql-12] [15-8] FROM "prom_data"."atlas_request_latency_nanoseconds_bucket" metric
[tsdb-3f573f18-1] 2021-04-16T06:02:01.917153 [postgresql-12] [15-9] WHERE metric.series_id = series.id
[tsdb-3f573f18-1] 2021-04-16T06:02:01.917185 [postgresql-12] [15-10] AND time >= '2021-04-15T05:59:00Z'
[tsdb-3f573f18-1] 2021-04-16T06:02:01.917216 [postgresql-12] [15-11] AND time <= '2021-04-16T06:00:00Z'
[tsdb-3f573f18-1] 2021-04-16T06:02:01.917250 [postgresql-12] [15-12] ORDER BY time
[tsdb-3f573f18-1] 2021-04-16T06:02:01.917283 [postgresql-12] [15-13] ) as time_ordered_rows
[tsdb-3f573f18-1] 2021-04-16T06:02:01.917318 [postgresql-12] [15-14] ) as result ON (result.value_array is not null)
[tsdb-3f573f18-1] 2021-04-16T06:02:01.917351 [postgresql-12] [15-15] WHERE
[tsdb-3f573f18-1] 2021-04-16T06:02:01.917382 [postgresql-12] [15-16] labels && (SELECT COALESCE(array_agg(l.id), array[]::int[]) FROM _prom_catalog.label l WHERE l.key = $1 and l.value = $2)
[tsdb-3f573f18-1] 2021-04-16T06:02:01.917416 [postgresql-12] [15-17] pid=178306,user=tsdbadmin,db=metrics,app=promscale@0.3.0,client=10.0.11.210 DETAIL: parameters: $1 = 'namespace', $2 = 'production'

TIMEOUT (1min)

===========================================================

https://grafana.abiosgaming.com/api/datasources/proxy/17/api/v1/query_range?query=histogram_quantile(0.99, sum by ( method, le)(rate(atlas_request_latency_nanoseconds_bucket{namespace="production"} [1m])))&start=1618466880&end=1618553280&step=120

[tsdb-3f573f18-1] 2021-04-16T06:09:22.876683 [postgresql-12] [15-1] pid=182123,user=tsdbadmin,db=metrics,app=promscale@0.3.0,client=10.0.11.210 LOG: duration: 8411.386 ms execute lrupsc_839_9: SELECT series.labels, result.time_array, result.value_array
[tsdb-3f573f18-1] 2021-04-16T06:09:22.877070 [postgresql-12] [15-2] FROM "prom_data_series"."atlas_request_latency_nanoseconds_bucket" series
[tsdb-3f573f18-1] 2021-04-16T06:09:22.877107 [postgresql-12] [15-3] INNER JOIN LATERAL (
[tsdb-3f573f18-1] 2021-04-16T06:09:22.877130 [postgresql-12] [15-4] SELECT array_agg(time) as time_array, array_agg(value) as value_array
[tsdb-3f573f18-1] 2021-04-16T06:09:22.877151 [postgresql-12] [15-5] FROM
[tsdb-3f573f18-1] 2021-04-16T06:09:22.877174 [postgresql-12] [15-6] (
[tsdb-3f573f18-1] 2021-04-16T06:09:22.877198 [postgresql-12] [15-7] SELECT time, value
[tsdb-3f573f18-1] 2021-04-16T06:09:22.877224 [postgresql-12] [15-8] FROM "prom_data"."atlas_request_latency_nanoseconds_bucket" metric
[tsdb-3f573f18-1] 2021-04-16T06:09:22.877246 [postgresql-12] [15-9] WHERE metric.series_id = series.id
[tsdb-3f573f18-1] 2021-04-16T06:09:22.877268 [postgresql-12] [15-10] AND time >= '2021-04-15T06:07:00Z'
[tsdb-3f573f18-1] 2021-04-16T06:09:22.877291 [postgresql-12] [15-11] AND time <= '2021-04-16T06:08:00Z'
[tsdb-3f573f18-1] 2021-04-16T06:09:22.877314 [postgresql-12] [15-12] ORDER BY time
[tsdb-3f573f18-1] 2021-04-16T06:09:22.877338 [postgresql-12] [15-13] ) as time_ordered_rows
[tsdb-3f573f18-1] 2021-04-16T06:09:22.877363 [postgresql-12] [15-14] ) as result ON (result.value_array is not null)
[tsdb-3f573f18-1] 2021-04-16T06:09:22.877384 [postgresql-12] [15-15] WHERE
[tsdb-3f573f18-1] 2021-04-16T06:09:22.877406 [postgresql-12] [15-16] labels && (SELECT COALESCE(array_agg(l.id), array[]::int[]) FROM _prom_catalog.label l WHERE l.key = $1 and l.value = $2)
[tsdb-3f573f18-1] 2021-04-16T06:09:22.877431 [postgresql-12] [15-17] pid=182123,user=tsdbadmin,db=metrics,app=promscale@0.3.0,client=10.0.11.210 DETAIL: parameters: $1 = 'namespace', $2 = 'production'

48.65s

===========================================================

Prometheus finishes the same query in ~10 seconds reliably
```

Here's some more information about that specific metric

```
metrics=> select count(*) from prom_info.metric;
-[ RECORD 1 ]
count | 1427
```

```
metrics=> select * from prom_info.metric where metric_name='atlas_request_latency_nanoseconds_bucket';
-[ RECORD 1 ]------------+------------------------------------------------------------------------------------------------------------------------------------
id                       | 675
metric_name              | atlas_request_latency_nanoseconds_bucket
table_name               | atlas_request_latency_nanoseconds_bucket
label_keys               | {container,endpoint,instance,job,le,method,__name__,namespace,pod,prometheus,prometheus_replica,route_template,service,status_code}
retention_period         | 90 days
chunk_interval           | 07:58:58.658076
compressed_interval      | 47:53:51.948456
total_interval           | 55:52:50.606532
before_compression_bytes | 3222134784
after_compression_bytes  | 33767424
total_size_bytes         | 269991936
total_size               | 257 MB
compression_ratio        | 98.95201702400292886100
total_chunks             | 7
compressed_chunks        | 6
```

The label-cardinality is quite high since it includes HTTP method, status code and route template. However, I would expect Timescale to handle this better than vanilla Prometheus.
