### ISSUE TITLE
"failed to connect to `host=localhost user=postgres database=timescale`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"

### ISSUE THREAD

**Issue by callrua** [timescale/promscale#467]
[docker-compose.yml.txt](https://github.com/timescale/promscale/files/5904888/docker-compose.yml.txt)
```
[r.callaghan@host ~ monitoring]$ sudo podman logs 29e9b4ccadb3
unknown seccomp syscall `clock_adjtime64` ignored
unknown seccomp syscall `clock_getres_time64` ignored
unknown seccomp syscall `clock_gettime64` ignored
unknown seccomp syscall `clock_nanosleep_time64` ignored
unknown seccomp syscall `faccessat2` ignored
unknown seccomp syscall `openat2` ignored
unknown seccomp syscall `pidfd_getfd` ignored
unknown seccomp syscall `ppoll_time64` ignored
unknown seccomp syscall `pselect6_time64` ignored
unknown seccomp syscall `timer_gettime64` ignored
unknown seccomp syscall `timerfd_gettime64` ignored
unknown seccomp syscall `timerfd_settime64` ignored
unknown seccomp syscall `utimensat_time64` ignored
level=info ts=2021-02-01T12:57:16.000Z caller=runner.go:149 msg="Version:0.1.4; Commit Hash: "
level=info ts=2021-02-01T12:57:16.000Z caller=runner.go:150 config="&{ListenAddr::9201 PgmodelCfg:{Host:localhost Port:5432 User:postgres password:**** Database:timescale SslMode:allow DbConnectRetries:10 AsyncAcks:false ReportInterval:0 LabelsCacheSize:10000 MetricsCacheSize:10000 SeriesCacheSize:0 WriteConnectionsPerProc:4 MaxConnections:-1 UsesHA:false DbUri:} LogCfg:{Level:debug Format:logfmt} APICfg:{AllowedOrigin:^(?:.*)$ ReadOnly:false AdminAPIEnabled:false TelemetryPath:/metrics-text Auth:0xc00023a410} ConfigFile:config.yml TLSCertFile: TLSKeyFile: HaGroupLockID:0 PrometheusTimeout:-1ns ElectionInterval:5s Migrate:true StopAfterMigrate:false UseVersionLease:true InstallTimescaleDB:true}"
level=error ts=2021-02-01T12:57:16.005Z caller=runner.go:160 msg="aborting startup due to error" err="failed to connect to `host=localhost user=postgres database=timescale`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)"
```

Seeing the above when attempting to spin up timescaledev/promscale-extension:latest-ts1-pg12 and timescale/promscale:latest.
Tried to get around the race-condition with 'restart: on-failure' and have -db-ssl-mode=allow set. Connecting to the database looks OK, so don't think it's a network problem.

```
[r.callaghan]$ sudo podman ps -a
CONTAINER ID  IMAGE                                                       COMMAND               CREATED        STATUS                    PORTS                   NAMES
40c40011b8f3  docker.io/timescaledev/promscale-extension:latest-ts1-pg12  -c hba_file=/var/...  3 minutes ago  Up 3 minutes ago          0.0.0.0:5432->5432/tcp  timescale_db
8fa9a63286da  docker.io/prom/node-exporter:latest                                               3 minutes ago  Up 3 minutes ago          0.0.0.0:9100->9100/tcp  node_exporter
fd96417c0c8f  docker.io/prom/prometheus:latest                            --web.enable-life...  3 minutes ago  Up 3 minutes ago          0.0.0.0:9090->9090/tcp  prometheus
57a5f04ec414  docker.io/grafana/grafana:latest                                                  3 minutes ago  Up 3 minutes ago          0.0.0.0:3000->3000/tcp  grafana
29e9b4ccadb3  docker.io/timescale/promscale:latest                        -db-ssl-mode=allo...  3 minutes ago  Exited (1) 3 minutes ago  0.0.0.0:9201->9201/tcp  timescale_promscale

[r.callaghan]$ psql -h localhost -p 5432 -U postgres  -d timescale
Password for user postgres: 
psql (10.15, server 12.4)
WARNING: psql major version 10, server major version 12.
         Some psql features might not work.
Type "help" for help.

timescale=# 
```

Am I doing something dumb? :)  
Attached my docker-compose.yml file - the pg_hba.conf being mounted is just a default file with the following appended.

```
host all all all md5
```

**Comment by callrua** [comment]
Looks like I am just hitting the race condition and there's an issue with the restart on-failure taking effect, #468

**Comment by VineethReddy02** [comment]
Hi @callrua 

There few issues in the `docker-compose` file you shared

1. In Promscale env variables `PROMSCALE_DB_HOST` is set to `localhost` in containers `localhost` points to local network of that container where DB i.e. TimescaleDB is not available this needs to be changed to `timescale_db` the service name of TimescaleDB as you defined in compose file. 
2. By default Promscale tries to use the database name as `timescaledb` if not explicitly provided but the TimescaleDB image you are using doesn't have a database with such a name by default so either create one or provide `PROMSCALE_DB_NAME` as `postgres` in Promscale env variables. 
3. I see twice `ssl-mode` configured to allow in Promscale i.e `PROMSCALE_DB_SSL_MODE: allow` & `   command: -db-ssl-mode=allow` you can drop command argument here. (But this isn't a reason for Promscale dial error). 

For more details on setting up **Promscale, TimescaleDB & Prometheus** using docker-compose you can use this [docker-compose file](https://github.com/timescale/promscale/blob/master/build/docker-compose.yml)

I hope this answers your question & helps you in running Promscale.

**Comment by callrua** [comment]
Hey @VineethReddy02,

Thanks for taking a look at the compose file!

1) I noticed this too and have corrected it to match the container name.
2) Good to know.
3) Will remove the command for this.

After correcting 1) I am still seeing the issue with the container failing to start - I do suspect it's the race condition that has been mentioned in this repo before. I raised #468 for that - essentially, the restart: on-failure doesn't seem to be being applied.

I'm happy to close this one out and look at the race condition with compose under #468.

Cheers,
Ruairi

**Comment by VineethReddy02** [comment]
I don't think it's the race condition. I personally use `docker-compose` very often never faced this issue in the past. Did you update database name to `postgres` as mentioned in point 2 of my previous comment?

**Comment by callrua** [comment]
Yep, I did.

```
[r.callaghan@monitoring]$ pod-up
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Creating network "paas-monitoring_default" with the default driver
Creating timescale_db  ... done
Creating prometheus    ... done
Creating node_exporter ... done
Creating grafana       ... done
Creating timescale_promscale ... done

[r.callaghan@monitoring]$ pod-ps
CONTAINER ID  IMAGE                                                       COMMAND               CREATED             STATUS                         PORTS                   NAMES
3628ca599d36  docker.io/timescaledev/promscale-extension:latest-ts1-pg12  -csynchronous_com...  About a minute ago  Up About a minute ago          0.0.0.0:5432->5432/tcp  timescale_db
0cb8a90535ee  docker.io/prom/node-exporter:latest                                               About a minute ago  Up About a minute ago          0.0.0.0:9100->9100/tcp  node_exporter
5f1d3c971717  docker.io/grafana/grafana:latest                                                  About a minute ago  Up About a minute ago          0.0.0.0:3000->3000/tcp  grafana
377a3437135e  docker.io/prom/prometheus:latest                            --web.enable-life...  About a minute ago  Up About a minute ago          0.0.0.0:9090->9090/tcp  prometheus
69989419f52c  docker.io/timescale/promscale:latest                                              About a minute ago  Exited (1) About a minute ago  0.0.0.0:9201->9201/tcp  timescale_promscale

```

```
 timescale_db:
   container_name: timescale_db
   image: docker.io/timescaledev/promscale-extension:latest-ts1-pg12
   #image: localhost/vela/timescale_db:latest
   command: -csynchronous_commit=off #-c hba_file=/var/lib/postgresql/docker_configs/pg_hba.conf
   ports:
     - "5432:5432/tcp"
   volumes:
     - ./config/timescale_db/:/var/lib/postgresql/docker_configs/
     - timescale_data:/var/lib/postgresql/data
   environment:
     POSTGRES_PASSWORD: postgres
     POSTGRES_USER: postgres
     POSTGRES_DB: postgres

 timescale_promscale:
   container_name: timescale_promscale
   image: docker.io/timescale/promscale:latest
   ports:
     - "9201:9201/tcp"
   build:
     context: .
   restart: on-failure
   #command: -db-ssl-mode=allow #-db-password=postgres -db-name=postgres -db-host=timescale_db
   depends_on:
     - timescale_db
     - prometheus
   environment:
     PROMSCALE_LOG_LEVEL: debug
     PROMSCALE_DB_CONNECT_RETRIES: 10
     PROMSCALE_DB_HOST: timescale_db
     PROMSCALE_DB_NAME: postgres
     PROMSCALE_DB_PASSWORD: postgres
     PROMSCALE_WEB_TELEMETRY_PATH: /metrics-text
     PROMSCALE_DB_SSL_MODE: allow
```
