### ISSUE TITLE
Is the prometheus /metrics endpoint supposed to be persistent on container restarts?

### ISSUE THREAD

**Issue by toymachiner62** [timescale/promscale#630]
I have a setup i'm where I have 2 containers in an AWS ECS task, one being a prometheus container and one being a promscale container. 

I'm pointing my promscale container to timescaledb on timescale cloud.

This is working well in that when I hit my prometheus container's `/metrics` endpoint I see my custom metrics that I created in my app.

If I restart my ECS task which restarts my prometheus and promscale containers, my prometheus `/metrics` endpoint data is reset. So is my grafana panel which i'm querying my promscale container via promQL. 

I thought promscale was supposed to persist the data so that I can make promQL queries to promscale and not having my data reset when the containers are restarted. Am I misunderstanding how this should work?

I have this same config snippet in my `prometheus.yml` file as mentioned here https://docs.timescale.com/timescaledb/latest/tutorials/promscale/promscale-install/#install-prometheus

```yaml
remote_write:
  - url: "http://promscale:9201/write"
remote_read:
  - url: "http://promscale:9201/read"
    read_recent: true
```
