### ISSUE TITLE
View "prom_info.metric" does not work for vanilla PostgreSQL

### ISSUE THREAD

**Issue by brunokoeferli** [timescale/promscale#738]
Querying the view "prom_info.metric" throws an error in case of a vanilla PostgreSQL database without any extension.
Query: `select * from prom_info.metric;`
Error: `ERROR:  column reference "id" is ambiguous at character 27`
PostgreSQL: v13
Promscale: `PROMSCALE_INSTALL_EXTENSIONS: "false"`

PostgreSQL log:
```
2021-09-09 13:28:09.043 UTC [128] ERROR:  column reference "id" is ambiguous at character 27
2021-09-09 13:28:09.043 UTC [128] DETAIL:  It could refer to either a PL/pgSQL variable or a table column.
2021-09-09 13:28:09.043 UTC [128] QUERY:  SELECT
                        id,
                        metric_name,
                        table_name,
                        label_keys,
                        retention_period,
                        chunk_interval,
                        NULL::interval compressed_interval,
                        NULL::interval total_interval,
                        pg_size_bytes(total_size) as before_compression_bytes,
                        NULL::bigint as after_compression_bytes,
                        pg_size_bytes(total_size) as total_size_bytes,
                        total_size,
                        compression_ratio,
                        total_chunks,
                        compressed_chunks
                     FROM
                     (
                         SELECT
                             m.id,
                             m.metric_name,
                             m.table_name,
                             ARRAY(
                                 SELECT key
                                 FROM _prom_catalog.label_key_position lkp
                                 WHERE lkp.metric_name = m.metric_name
                                 ORDER BY key) label_keys,
                             _prom_catalog.get_metric_retention_period(m.metric_name) as retention_period,
                             NULL::interval as chunk_interval,
                             pg_size_pretty(pg_total_relation_size(format('prom_data.%I', m.table_name)::regclass)) as total_size,
                             0.0 as compression_ratio,
                             NULL::bigint as total_chunks,
                             NULL::bigint as compressed_chunks
                         FROM _prom_catalog.metric m
                     ) AS i
2021-09-09 13:28:09.043 UTC [128] CONTEXT:  PL/pgSQL function _prom_catalog.metric_view() line 4 at RETURN QUERY
2021-09-09 13:28:09.043 UTC [128] STATEMENT:  select * from metric_view()
```

The problem is caused by using column names without an alias, e.g. `id` instead of `i.id`.

**Comment by brunokoeferli** [comment]
Sample docker compose setup:
```yaml
version: '3.0'

services:
  db:
    image: postgres:12
    ports:
      - 5432:5432/tcp
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres

  promscale:
    image: timescale/promscale:latest
    ports:
      - 9201:9201/tcp
    restart: on-failure
    depends_on:
      - db
      - prometheus
    environment:
      PROMSCALE_DB_CONNECT_RETRIES: 10
      PROMSCALE_WEB_TELEMETRY_PATH: /metrics-text
      PROMSCALE_DB_URI: postgres://postgres:password@db:5432/postgres?sslmode=allow
      PROMSCALE_INSTALL_EXTENSIONS: "false"
```
