### ISSUE TITLE
Rethink how tracing is enabled in helm chart

### ISSUE THREAD

**Issue by JamesGuthrie** [timescale/promscale#918]
Since we added `-enable-feature=tracing` to turn on tracing, the helm chart config to enable tracing now must be as follows:

```yaml
args:
- -enable-feature=tracing
- -otlp-grpc-server-listen-address=:9202
tracing:
  enabled: true
```

This is redundant and verbose. The following would be convenient:

```yaml
tracing:
  enabled: true
```

(Although what happens when tracing becomes GA and is enabled by default?)

**Comment by zcourts** [comment]
Just trying to test this and can't get it installed with or without disabled tracing. 
When tracing is on it says it requires cert-manager because of the transitive dep, understandable but even when tracing.enabled is false it is still trying to create cert-manager related CRDs.

We don't have cert-manager and can't use it because it conflicts with our own PKI.
Is it not possible for promscale to depend on https://github.com/open-telemetry/opentelemetry-collector which doesn't have the cert-manager dep instead of the operator?

```
        tracing:
          enabled: false
        args: []
#         - "-otlp-grpc-server-listen-address=:9202"
```
Above fails trying to create `Certificate` CRD
