### ISSUE TITLE
Can't connect to external timescaleDB

### ISSUE THREAD

**Issue by kevinlmadison** [timescale/promscale#994]
I'm seeing this error
```
level=error ts=2021-12-17T19:33:07.481Z caller=runner.go:50 msg="aborting startup due to error" err="cannot parse `postgresql://postgres:xxxxxx@timescale-primary.monitoring.svc.cluster.local:xxxxxx@0.6.1&sslmode=require&connect_timeout=60`: failed to parse as URL (parse \"postgresql://postgres:)[xTNEf2w-XE(*+R|J]?}{m(@timescale-primary.monitoring.svc.cluster.local:5432/postgres?application_name=promscale@0.6.1&sslmode=require&connect_timeout=60\": invalid port \":)[xTNEf2w-XE(*+R|J]\" after host)"
```
and I've tried using both helm and tobs to install using this set of values
```
timescaledb-single:
  enalbed: false
  backup:
    enabled: false
timescaledbExternal:
  enalbed: true
promscale:
  enalbed: true
  connection:
    dbName: postgres
    user: postgres
    password:
      secretTemplate: "timescale-pguser-postgres"
      timescaleDBSuperUserKey: password
    host:
      nameTemplate: "timescale-primary.monitoring.svc.cluster.local"
    port: 5432
kube-prometheus-stack:
  enabled: false
  alertmanager:
    enabled: false
  grafana:
    enabled: false
  fullNameOverride: false
opentelemetryOperator:
  enabled: false
```
Am I doing this wrong?
